# these config valies are overridden by those passed through the
# jekyll section of the grunt.js file if built via grunt.
auto:           false
server:         false
server_port:    8000
port: 8000
source:         src
destination:    _site
pygments:       true
tag_dir:        /blog/tag
permalink:      /blog/:title
