# these config valies are overridden by those passed through the
# jekyll section of the grunt.js file if built via grunt.
auto:           true
server:         true
server_port:    8000
port: 8000
source:         src
destination:    _site
pygments:       true
tag_dir:        /blog/tag
permalink:      /blog/:title
sass:
    syntax: scss        # scss|sass
    style:  nested  # nested|expanded|compact|compressed
