url: https://www.hawksworx.com
port: 4000
source:         ./src
destination:    ./_site
plugins_dir:    ./_plugins
tag_dir:        /blog/tag
permalink:      /blog/:title/
sass:
  sass_dir: css/_scss
  style:  compressed
