baseURL: "https://gohugo--hawksworx.netlify.com"
title: "Hawksworx - Phil Hawksworth"
theme: "./simple-starter"
publishDir: "dist"
enableGitInfo: true

outputFormats:
  card:
    mediaType: "text/html"
    baseName: "card"
    isHTML: true

outputs:
  home:
    - "html"
    - "card"
  page:
    - "html"
    - "card"
  section:
    - "html"
    - "card"
