[build]
  Functions = "functions"



[[headers]]

 for = "/*"
 [headers.values]
   X-Frame-Options = "DENY"
   X-XSS-Protection = "1; mode=block"
   Content-Security-Policy = "script-src 'unsafe-inline' https://www.hawksworx.com:* https://*.netlify.com:* https://www.google-analytics.com:*"
   X-Content-Type-Options = "nosniff"
   Referrer-Policy= "no-referrer-when-downgrade"



# Simplify requests for my headshots
[[redirects]]
  from = "/philhawksworth-*"
  to = "/images/philhawksworth-:splat"

# Look after the old use of journal in urls
[[redirects]]
  from = "/journal*"
  to = "/blog:splat"
  status = 301

# Simplified blog urls for slugs
[[redirects]]
  from = "/blog/:year/:month/:day/:slug"
  to = "/blog/:slug"
  status = 301

# Proxy puttr seaches to my search lambda
[[redirects]]
  from = "/puttr/api"
  to = "https://w04p8v061j.execute-api.us-east-1.amazonaws.com:443/dev/listings"
  status = 200

# Talks and sldes
[[redirects]]
  from = "/talks"
  to = "/speaking"
  status = 302

# Talks and sldes
[[redirects]]
  from = "/talks/scriptconf"
  to = "https://speakerdeck.com/philhawksworth/next-wave-infrastructure"
  status = 302

  [[redirects]]
  from = "/talks/scriptcom"
  to = "https://speakerdeck.com/philhawksworth/next-wave-infrastructure"
  status = 302

